version: '3.1'

services:
  front:
    build:
      context: frontend
      dockerfile: Dockerfile
      args:
        PORT: ${FRONTEND_PORT}
    container_name: tm_web
    ports:
      - '${FRONTEND_PORT}:${FRONTEND_PORT}'
  api:
    build:
      context: api
      dockerfile: Dockerfile
      args:
        PORT: ${API_PORT}
    container_name: tm_api
    ports:
      - '${API_PORT}:${API_PORT}'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_PROD_HOST}
      FRONTEND_URL: ${FRONTEND_URL}
      API_PORT: ${API_PORT}
    depends_on:
      - db
  db:
    image: postgres
    container_name: tm_db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}

  adminer:
    image: adminer
    container_name: tm_adminer
    restart: always
    ports:
      - '8080:8080'
  server_web:
    image: nginx
    volumes:
      - ./nginx.prod.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    command: [nginx-debug, '-g', 'daemon off;']
    ports:
      - '80:80'
      - '443:443'
    depends_on:
    - front
    restart: always
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
