version: '3.1'

services:
  api:
    build:
      context: api
      dockerfile: Dockerfile
    container_name: tm_api
    ports:
      - '4000:4000'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_PROD_HOST}
    networks:
      - TM
    depends_on:
      - db
  db:
    image: postgres
    container_name: tm_db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - TM

  adminer:
    image: adminer
    container_name: tm_adminer
    restart: always
    ports:
      - '8080:8080'
    networks:
      - TM
networks:
  TM:
    driver: bridge
