name: build docker images
on:
  push:
    branches:
      - 'main'
      - 'devops/github_ci'
  pull_request:
    branches: [ main ]
jobs:
  build-docker-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Create envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          envkey_POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          envkey_POSTGRES_DB: tm_db
          envkey_POSTGRES_HOST: localhost
          envkey_POSTGRES_PROD_HOST: db
          envkey_JWT_SECRET: JWT_SECRET
          envkey_API_URL: http://localhost:4000
          envkey_FRONTEND_URL: *
          envkey_FRONTEND_PORT: 4500
          envkey_API_PORT: 4000
          file_name: .env
          fail_on_empty: false
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push API
        uses: docker/build-push-action@v3
        with:
          context: api
          push: true
          tags: frnikho/timemanager-api:latest
      - name: Build and push FRONT
        uses: docker/build-push-action@v3
        with:
          context: frontend
          push: true
          tags: frnikho/timemanager-front:latest