name: Deploy
on:
  push:
    branches: [main, deploy-1]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: git pull
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          password: ${{secrets.SSH_PASSWORD}}
          username: ${{secrets.SSH_USERNAME}}
          script: |
            cd TimeManagerMirror
            git rebase

      - name: docker Build
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          password: ${{secrets.SSH_PASSWORD}}
          username: ${{secrets.SSH_USERNAME}}
          script: |
            cd TimeManagerMirror
            docker-compose down
            docker-compose up --build -d
